{
  "name": "Dots",
  "base": "{{ mode }}",
  "overrides": {
    "claude": "{{ accent }}",
    "claudeShimmer": "{{ bright_blue }}",
    "text": "{{ foreground }}",
    "inverseText": "{{ background }}",
    "inactive": "{{ dark_foreground }}",
    "inactiveShimmer": "{{ muted }}",
    "subtle": "{{ muted }}",
    "suggestion": "{{ cyan }}",
    "permission": "{{ blue }}",
    "permissionShimmer": "{{ bright_blue }}",
    "remember": "{{ yellow }}",
    "success": "{{ green }}",
    "error": "{{ red }}",
    "warning": "{{ yellow }}",
    "warningShimmer": "{{ bright_yellow }}",
    "merged": "{{ magenta }}",
    "promptBorder": "{{ accent }}",
    "promptBorderShimmer": "{{ bright_blue }}",
    "planMode": "{{ cyan }}",
    "autoAccept": "{{ yellow }}",
    "bashBorder": "{{ bright_yellow }}",
    "ide": "{{ bright_cyan }}",
    "diffAdded": "{{ dark_background }}",
    "diffRemoved": "{{ darker_background }}",
    "diffAddedDimmed": "{{ background }}",
    "diffRemovedDimmed": "{{ background }}",
    "diffAddedWord": "{{ selection }}",
    "diffRemovedWord": "{{ selection }}",
    "userMessageBackground": "{{ dark_background }}",
    "userMessageBackgroundHover": "{{ lighter_background }}",
    "bashMessageBackgroundColor": "{{ dark_background }}",
    "memoryBackgroundColor": "{{ dark_background }}",
    "selectionBg": "{{ selection_background }}",
    "rate_limit_fill": "{{ accent }}",
    "rate_limit_empty": "{{ muted }}",
    "briefLabelYou": "{{ yellow }}",
    "briefLabelClaude": "{{ accent }}"
  }
}
