{
  "$schema": "https://raw.githubusercontent.com/earendil-works/pi/main/packages/coding-agent/src/modes/interactive/theme/theme-schema.json",
  "name": "dots-system",
  "vars": {
    "background": "{{ background }}",
    "foreground": "{{ foreground }}",
    "accent": "{{ accent }}",
    "selectionBackground": "{{ selection_background }}",
    "selectionForeground": "{{ selection_foreground }}",
    "selectedBackground": "{{ selection }}",
    "color0": "{{ background }}",
    "color1": "{{ red }}",
    "color2": "{{ green }}",
    "color3": "{{ yellow }}",
    "color4": "{{ blue }}",
    "color5": "{{ magenta }}",
    "color6": "{{ cyan }}",
    "color7": "{{ foreground }}",
    "color8": "{{ muted }}",
    "color9": "{{ bright_red }}",
    "color10": "{{ bright_green }}",
    "color11": "{{ bright_yellow }}",
    "color12": "{{ bright_blue }}",
    "color13": "{{ bright_magenta }}",
    "color14": "{{ bright_cyan }}",
    "color15": "{{ bright_foreground }}",
    "panel": "{{ dark_background }}",
    "panelAlt": "{{ lighter_background }}",
    "panelPending": "{{ selection }}",
    "panelSuccess": "{{ dark_background }}",
    "panelError": "{{ darker_background }}",
    "border": "{{ dark_foreground }}",
    "borderMuted": "{{ muted }}",
    "mutedText": "{{ dark_foreground }}",
    "dimText": "{{ muted }}"
  },
  "colors": {
    "accent": "accent",
    "border": "border",
    "borderAccent": "accent",
    "borderMuted": "borderMuted",
    "success": "color2",
    "error": "color1",
    "warning": "color3",
    "muted": "mutedText",
    "dim": "dimText",
    "text": "foreground",
    "thinkingText": "dimText",
    "selectedBg": "selectedBackground",
    "userMessageBg": "panel",
    "userMessageText": "foreground",
    "customMessageBg": "panel",
    "customMessageText": "foreground",
    "customMessageLabel": "accent",
    "toolPendingBg": "panelPending",
    "toolSuccessBg": "panelSuccess",
    "toolErrorBg": "panelError",
    "toolTitle": "accent",
    "toolOutput": "foreground",
    "mdHeading": "color5",
    "mdLink": "accent",
    "mdLinkUrl": "color6",
    "mdCode": "color6",
    "mdCodeBlock": "foreground",
    "mdCodeBlockBorder": "borderMuted",
    "mdQuote": "mutedText",
    "mdQuoteBorder": "borderMuted",
    "mdHr": "borderMuted",
    "mdListBullet": "color5",
    "toolDiffAdded": "color2",
    "toolDiffRemoved": "color1",
    "toolDiffContext": "mutedText",
    "syntaxComment": "dimText",
    "syntaxKeyword": "color5",
    "syntaxFunction": "color4",
    "syntaxVariable": "accent",
    "syntaxString": "color2",
    "syntaxNumber": "color3",
    "syntaxType": "color4",
    "syntaxOperator": "color5",
    "syntaxPunctuation": "mutedText",
    "thinkingOff": "borderMuted",
    "thinkingMinimal": "accent",
    "thinkingLow": "color4",
    "thinkingMedium": "color5",
    "thinkingHigh": "color3",
    "thinkingXhigh": "color1",
    "bashMode": "color3"
  },
  "export": {
    "pageBg": "{{ background }}",
    "cardBg": "{{ dark_background }}",
    "infoBg": "{{ lighter_background }}"
  }
}
