# Generated by dots-theme-set. Loaded by ~/.config/tmux/tmux.conf.
set-option -g window-style "fg={{ foreground }},bg={{ background }}"
set-option -g window-active-style "fg={{ foreground }},bg={{ background }}"
set-option -g pane-border-style "fg={{ muted }}"
set-option -g pane-active-border-style "fg={{ accent }}"
set-option -g status-style "fg={{ foreground }},bg={{ background }}"
set-option -g mode-style "fg={{ selection_foreground }},bg={{ selection_background }}"
