[settings]
minimum_release_age = "0s"

[tools]
bat = "latest"
claude = "latest"
codex = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
"github:can1357/oh-my-pi" = "latest"
"github:kunchenguid/no-mistakes" = "latest"
go = "latest"
gum = "latest"
herdr = "latest"
jq = "latest"
lazygit = "latest"
neovim = "latest"
node = "lts"
"npm:stepstone" = "latest"
opencode = "latest"
pi = "latest"
python = "latest"
ripgrep = "latest"
starship = "latest"
tmux = "latest"
zoxide = "latest"
